---
abstract: 'AI::MicroStructure   Creates Concepts for words'
author:
  - 'santex <santex@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-MicroStructure
requires:
  AnyDBM_File: 0
  AnyEvent::Subprocess::Easy: 0
  Carp: 0
  Data::Dumper: 0
  Data::Format::Pretty::Console: 0
  Data::Printer: 0
  Digest::MD5: 0
  Fcntl: 0
  File::Basename: 0
  File::Glob: 0
  File::Spec: 0
  Getopt::Long: 0
  HTML::Strip: 0
  IO::Page: 0
  JSON: 0
  JSON::XS: 0
  List::Util: 0
  Statistics::Basic: 0
  Storable: 0
  Storable::CouchDB: 0
  Term::ReadKey: 0
  URI::Escape: 0
  WWW::Wikipedia: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.009
